---
- name: Deploy Web Server
  hosts: webserver1:webserver2
  become: yes
  tasks:
    - name: Stop Apache service
      service:
        name: httpd
        state: stopped

    - name: Remove index.html file
      file:
        path: /var/www/html/index.html
        state: absent
